version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2345:80'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: 'mariadb'
    restart: always
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: password
    volumes:
    # Pour lancer un dump automatiquement au montage du conteneur
    - ./data.sql:/docker-entrypoint-initdb.d/dump.sql



  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1

  #node:
    #build:
      #context: .
      #dockerfile: Dockerfile
    #user: "node"
    #working_dir: /var/www/html
    #environment:
      #- NODE_ENV=production
    #volumes:
     # - ./app/wp-content/themes/wik-theme:/var/www/html
